# Generated by Django 5.2.10 on 2026-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('user_agent', models.TextField()),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('request_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('NORMAL', 'Normal'), ('SUSPICIOUS', 'Suspicious'), ('MALICIOUS', 'Malicious')], default='NORMAL', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
