# Generated by Django 5.2.10 on 2026-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='attack_type',
            field=models.CharField(default='NORMAL', max_length=50),
        ),
    ]
