# Generated by Django 5.2.10 on 2026-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_behaviorlog_attack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='keyword_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='param_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='payload_size',
            field=models.IntegerField(default=0),
        ),
    ]
