# Generated by Django 5.2.10 on 2026-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_behaviorlog_keyword_count_behaviorlog_param_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='request_interval',
            field=models.FloatField(default=0),
        ),
    ]
