# Generated by Django 5.2.10 on 2026-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_behaviorlog_request_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
