# Generated by Django 5.2.10 on 2026-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_behaviorlog_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='last_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='same_user_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
